apiVersion: v1
kind: Service
metadata:
  name: egov-login-policy
  labels:
    app.kubernetes.io/name: egov-login-policy
    app.kubernetes.io/part-of: egovframe-msa-common
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: egov-login-policy
  ports:
    - name: http
      port: 8080
      targetPort: http
