apiVersion: v1
kind: Service
metadata:
  name: egov-search
  labels:
    app.kubernetes.io/name: egov-search
    app.kubernetes.io/part-of: egovframe-msa-common
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: egov-search
  ports:
    - name: http
      port: 9992
      targetPort: http
