server:
  port: 8888

spring:
  application:
    name: ConfigServer
  profiles:
    active: native # 로컬 파일시스템 기반 저장소 사용
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config # 설정 파일 경로 (jar 내부 또는 src/main/resources/config)

management:
  endpoints:
    access:
      default: read-only # 기본적으로 모든 엔드포인트를 읽기 전용으로 설정
    jmx:
      exposure:
        exclude: "*" # JMX에서 모든 엔드포인트 비활성화
    web:
      exposure:
        include: health, info

